spring.application.name=f1-api
springdoc.swagger-ui.path=/f1-documentation
springdoc.api-docs.path=/f1-api-docs
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true

f1.openapi.prod-url=TODO